ALTER TYPE "RolCliente" RENAME VALUE 'REGULAR' TO 'STANDARD_1';
ALTER TYPE "RolCliente" RENAME VALUE 'REGULAR_2' TO 'STANDARD_2';
ALTER TYPE "RolCliente" RENAME VALUE 'CARPINTERO' TO 'CARPINTERIA';
ALTER TYPE "RolCliente" RENAME VALUE 'PLOMERO' TO 'PLOMERIA';
ALTER TYPE "RolCliente" ADD VALUE 'ELECTRICISTA';
